[build]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "opt-level=3",
    "-C", "target-cpu=native",
    "-C", "codegen-units=1",
    "-C", "lto=fat",
]

[profile.release]
panic = "abort"
strip = true
codegen-units = 1
lto = true
opt-level = 3

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]